/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutKanbanRouteImport } from './routes/_layout.kanban'
import { Route as LayoutFormRouteImport } from './routes/_layout.form'
import { Route as LayoutAboutRouteImport } from './routes/_layout.about'
import { Route as LayoutTaskTaskIdRouteImport } from './routes/_layout.task.$taskId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutKanbanRoute = LayoutKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFormRoute = LayoutFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTaskTaskIdRoute = LayoutTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof LayoutAboutRoute
  '/form': typeof LayoutFormRoute
  '/kanban': typeof LayoutKanbanRoute
  '/task/$taskId': typeof LayoutTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof LayoutAboutRoute
  '/form': typeof LayoutFormRoute
  '/kanban': typeof LayoutKanbanRoute
  '/task/$taskId': typeof LayoutTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/form': typeof LayoutFormRoute
  '/_layout/kanban': typeof LayoutKanbanRoute
  '/_layout/task/$taskId': typeof LayoutTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/form' | '/kanban' | '/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/form' | '/kanban' | '/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/about'
    | '/_layout/form'
    | '/_layout/kanban'
    | '/_layout/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/kanban': {
      id: '/_layout/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof LayoutKanbanRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/form': {
      id: '/_layout/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof LayoutFormRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/task/$taskId': {
      id: '/_layout/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof LayoutTaskTaskIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutFormRoute: typeof LayoutFormRoute
  LayoutKanbanRoute: typeof LayoutKanbanRoute
  LayoutTaskTaskIdRoute: typeof LayoutTaskTaskIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutFormRoute: LayoutFormRoute,
  LayoutKanbanRoute: LayoutKanbanRoute,
  LayoutTaskTaskIdRoute: LayoutTaskTaskIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
